### ISSUE TITLE
Console Error - Going Into Game

### ISSUE THREAD

**Issue by ZakShearman** [gc2023/CheatsBeGone#92]
# Console Error
https://pastebin.com/DeDWPfLh

# When the bug occurrs?
Occurs when I teleport into and out of a Practice game sometimes.

# Server Version:
# Anticheat Version: 1.0
# ProtocolLib Version: 4.4.0
# Is the config file the newest?: (yes/no) Is there even a config?

**Comment by gc2023** [comment]
Fixed next update.

**Comment by ZakShearman** [comment]
Thanks.
