### ISSUE TITLE
Vape Bypass (Speed - Mineplex)

### ISSUE THREAD

**Issue by ZakShearman** [gc2023/CheatsBeGone#94]
# Hack Client: Vape
# Hacking Type: Speed - Mineplex
# Anticheat Version: 1.0
# Server Version: 1.8.8-Spigot

# Videos
UPLOADING - Will attach as soon as possible.

**Comment by ZakShearman** [comment]
Video here: https://zak.pink/19-04-22-42-21_770.mp4

**Comment by gc2023** [comment]
Yes, expect more bypasses of Bhops because there isnt a bhop based speed check yet. I will add one as soon as possible.

**Comment by ZakShearman** [comment]
Thanks.
