### ISSUE TITLE
Ender Pearl False Flag

### ISSUE THREAD

**Issue by ZakShearman** [gc2023/CheatsBeGone#95]
# How you trigger the false positive?
Ender Pearl

# Verbose Message:
IN VIDEO

# Videos:
https://zak.pink/19-04-22-46-07_771.mp4

# Anticheat Version: 1.0
# Server Version: 1.8.8-Spigot
# ProtocolLib Version: 4.4.0

**Comment by gc2023** [comment]
Do /ac verbose

Tell me which detection its flagging you for, for I cannot fix without knowing which detection your being detected for.

**Comment by ZakShearman** [comment]
https://zak.pink/19-04-22-55-10_772.png - Speed A
